const fs = require("fs");
const outPath = "D:/project/TradingAgents-astock/components/ReportSlideshow.tsx";
const lines = [];

// ====== HEADER ======
lines.push("'use client';");
lines.push("import React, { useEffect, useRef, useState, useCallback } from 'react';");
lines.push("");
lines.push("interface SlideshowProps {");
lines.push("  ticker: string;");
lines.push("  tickerName: string;");
lines.push("  tradeDate: string;");
lines.push("  signal?: { text: string; rating?: string; confidence?: number } | null;");
lines.push("  messages: { id: string; agent: string; label: string; side?: string; content: string; round?: number }[];");
lines.push("  report: string;");
lines.push("}");
lines.push("");
lines.push("const AGENT_ICONS: Record<string,string> = { market:'📉',social:'💬',news:'📰',fundamentals:'📊',policy:'🏛️',hot_money:'💰',lockup:'🔒',quality_gate:'✅',research_manager:'📋',trader:'💹',pm:'📦' };");
lines.push("const AGENT_LABELS: Record<string,string> = { market:'市场分析',social:'情绪分析',news:'新闻分析',fundamentals:'基本面分析',policy:'政策分析',hot_money:'资金分析',lockup:'解禁分析',quality_gate:'质量门控',research_manager:'研究主管',trader:'交易决策',pm:'投资组合' };");
lines.push("const RATING_MAP: Record<string,string> = { strong_buy:'Strong Buy',buy:'Buy',hold:'Hold',sell:'Sell',strong_sell:'Strong Sell' };");
lines.push("const RATING_CN: Record<string,string> = { strong_buy:'强烈建议买入',buy:'建议买入',hold:'持有观望',sell:'建议卖出',strong_sell:'强烈建议卖出' };");
lines.push("const RATING_COLOR: Record<string,string> = { strong_buy:'#00E676',buy:'#76FF03',hold:'#FFD740',sell:'#FF5252',strong_sell:'#D50000' };");
lines.push("const RATING_BG: Record<string,string> = { strong_buy:'rgba(0,230,118,0.15)',buy:'rgba(118,255,3,0.12)',hold:'rgba(255,215,64,0.12)',sell:'rgba(255,82,82,0.12)',strong_sell:'rgba(213,0,0,0.15)' };");
lines.push("");
lines.push("function getFromMsg(messages:any[],agent:string):string{const m=messages.find((msg:any)=>msg.agent===agent);return m?.content||''}");
lines.push("function extractScore(content:string):number|null{if(!content)return null;const m=content.match(/(?:评分|score)[：:]\\s*([0-9]+(?:\\.[0-9]+)?)/i);return m?parseFloat(m[1]):null}");
lines.push("function extractReg(content:string,pattern:RegExp):string{if(!content)return '';const m=content.match(pattern);return m?m[1]:''}");
lines.push("function extractOneLiner(content:string):string{if(!content)return '';const lines=content.split('\\n').filter(l=>l.trim().length>0);return lines.length>0?lines[0].replace(/^[-•*]\\s*/,'').trim():''}");
lines.push("function extractKPI(content:string,label:string,pattern:RegExp):{label:string;value:string;color?:string}{const v=extractReg(content,pattern);const isNeg=v.startsWith('-');return{label,value:v||'--',color:isNeg?'#FF5252':v?'#00E676':'#888'}}");

// ====== EXPORT FUNCTION ======
lines.push("");
lines.push("export default function ReportSlideshow({ ticker, tickerName, tradeDate, signal, messages, report }: SlideshowProps) {");
lines.push("  const [current, setCurrent] = useState(0);");
lines.push("  const [showHint, setShowHint] = useState(true);");
lines.push("  const [fullscreen, setFullscreen] = useState(false);");
lines.push("  const [chartLoaded, setChartLoaded] = useState(false);");
lines.push("  const containerRef = useRef<HTMLDivElement>(null);");
lines.push("  const touchX = useRef(0);");
lines.push("  const chartInstances = useRef<any[]>([]);");
lines.push("  const TOTAL_PAGES = 10;");

// ====== DERIVED DATA ======
lines.push("");
lines.push("  const marketContent = getFromMsg(messages, 'market');");
lines.push("  const socialContent = getFromMsg(messages, 'social');");
lines.push("  const hotMoneyContent = getFromMsg(messages, 'hot_money');");
lines.push("  const rating = signal?.rating || 'hold';");
lines.push("  const ratingTextCN = RATING_CN[rating] || rating;");
lines.push("  const ratingColor = RATING_COLOR[rating] || '#FFD740';");
lines.push("  const ratingBg = RATING_BG[rating] || 'rgba(255,215,64,0.12)';");
lines.push("  const isBullish = rating === 'strong_buy' || rating === 'buy';");
lines.push("  const isBearish = rating === 'sell' || rating === 'strong_sell';");

lines.push("  const agentKeys = ['market','social','hot_money','fundamentals','policy','lockup'];");
lines.push("  const coverageDims = agentKeys.map(k=>({key:k,score:extractScore(getFromMsg(messages,k))}));");
lines.push("  const coveragePct = Math.round(coverageDims.filter(d=>d.score!==null).length/coverageDims.length*100);");

lines.push("  const kpiItems:{label:string;value:string;color?:string}[] = [");
lines.push("    extractKPI(marketContent,'收盘价',/(?:收盘价|close|price)[：:]\\s*([0-9.]+)/),");
lines.push("    extractKPI(marketContent,'涨跌幅',/(?:涨跌幅|change|chg)[：:]\\s*([+-]?[0-9.]+%)/),");
lines.push("    extractKPI(marketContent,'成交量',/(?:成交量|volume|vol)[：:]\\s*([0-9.]+)/),");
lines.push("    extractKPI(marketContent,'换手率',/(?:换手率|turnover)[：:]\\s*([0-9.]+%)/),");
lines.push("  ];");

lines.push("  const actionItems = isBullish");
lines.push("    ? [{role:'持有者',emoji:'🧲',action:'继续持有，设好止损位即可',color:'#00E676'},{role:'观望者',emoji:'👀',action:'小仓位试探性介入，回调是机会',color:'#FFD740'},{role:'抄底者',emoji:'🦅',action:'确认支撑后可适当加仓',color:'#FF6B00'}]");
lines.push("    : isBearish");
lines.push("    ? [{role:'持有者',emoji:'🧲',action:'考虑减仓锁定利润，控制风险',color:'#FF5252'},{role:'观望者',emoji:'👀',action:'观望为主，等待明确企稳信号',color:'#FFD740'},{role:'抄底者',emoji:'🦅',action:'不建议盲目抄底，多看少动',color:'#888'}]");
lines.push("    : [{role:'持有者',emoji:'🧲',action:'谨慎持有，关注关键价位突破',color:'#FFD740'},{role:'观望者',emoji:'👀',action:'等待方向明确后再做决定',color:'#FFD740'},{role:'抄底者',emoji:'🦅',action:'不建议重仓，可以小仓位试盘',color:'#FF6B00'}]");

// ====== CHART JS LOADER ======
lines.push("");
lines.push("  useEffect(() => {");
lines.push("    if (typeof window === 'undefined') return;");
lines.push("    const s = document.createElement('script');");
lines.push("    s.src = 'https://cdn.jsdelivr.net/npm/chart.js@4';");
lines.push("    s.onload = () => setChartLoaded(true);");
lines.push("    document.head.appendChild(s);");
lines.push("    return () => { if (s.parentNode) document.head.removeChild(s); };");
lines.push("  }, []);");

// ====== CHART RENDER ======
lines.push("");
lines.push("  useEffect(() => {");
lines.push("    if (!chartLoaded) return;");
lines.push("    const C = (window as any).Chart;");
lines.push("    if (!C) return;");
lines.push("    const inst: any[] = [];");

// Fund chart
lines.push("    const f = document.getElementById('chart-fund') as HTMLCanvasElement;");
lines.push("    if (f) {");
lines.push("      const ctx = f.getContext('2d');");
lines.push("      if (ctx) {");
lines.push("        const c = new C(ctx, {");
lines.push("          type: 'bar',");
lines.push("          data: {");
lines.push("            labels: ['主力净流入','大单净流入','散户净流入'],");
lines.push("            datasets: [{");
lines.push("              label: '资金流向',");
lines.push("              data: [");
lines.push("                parseFloat(extractReg(getFromMsg(messages,'hot_money'),/主力.*?净[流进][：:]\\s*([+-]?[0-9]+(?:\\.[0-9]+)?)/)) || 0,");
lines.push("                parseFloat(extractReg(getFromMsg(messages,'hot_money'),/大单.*?净[流进][：:]\\s*([+-]?[0-9]+(?:\\.[0-9]+)?)/)) || 0,");
lines.push("                parseFloat(extractReg(getFromMsg(messages,'hot_money'),/散户.*?净[流进][：:]\\s*([+-]?[0-9]+(?:\\.[0-9]+)?)/)) || 0,");
lines.push("              ],");
lines.push("              backgroundColor: ['rgba(0,230,118,0.7)','rgba(0,229,255,0.7)','rgba(255,107,0,0.7)'],");
lines.push("              borderColor: ['#00E676','#00E5FF','#FF6B00'],");
lines.push("              borderWidth: 1,");
lines.push("            }],");
lines.push("          },");
lines.push("          options: {");
lines.push("            indexAxis: 'y', responsive: true, maintainAspectRatio: false,");
lines.push("            plugins: { legend: { display: false } },");
lines.push("            scales: {");
lines.push("              x: { grid: { color: 'rgba(255,255,255,0.05)' }, ticks: { color: '#888' } },");
lines.push("              y: { grid: { display: false }, ticks: { color: '#888' } },");
lines.push("            },");
lines.push("          },");
lines.push("        });");
lines.push("        inst.push(c);");
lines.push("      }");
lines.push("    }");

// Debate chart
lines.push("    const dC = document.getElementById('chart-debate') as HTMLCanvasElement;");
lines.push("    if (dC) {");
lines.push("      const ctx = dC.getContext('2d');");
lines.push("      if (ctx) {");
lines.push("        const bull = extractScore(getFromMsg(messages,'debate')) || 5;");
lines.push("        const c = new C(ctx, {");
lines.push("          type: 'bar',");
lines.push("          data: {");
lines.push("            labels: ['多方','空方'],");
lines.push("            datasets: [{");
lines.push("              label: '多空对比',");
lines.push("              data: [bull, 10 - bull],");
lines.push("              backgroundColor: ['rgba(0,230,118,0.7)','rgba(255,82,82,0.7)'],");
lines.push("              borderColor: ['#00E676','#FF5252'],");
lines.push("              borderWidth: 2,");
lines.push("              borderRadius: 4,");
lines.push("            }],");
lines.push("          },");
lines.push("          options: {");
lines.push("            responsive: true, maintainAspectRatio: false,");
lines.push("            plugins: { legend: { display: false } },");
lines.push("            scales: {");
lines.push("              y: { beginAtZero: true, max: 10, grid: { color: 'rgba(255,255,255,0.05)' }, ticks: { color: '#888' } },");
lines.push("              x: { grid: { display: false }, ticks: { color: '#888' } },");
lines.push("            },");
lines.push("          },");
lines.push("        });");
lines.push("        inst.push(c);");
lines.push("      }");
lines.push("    }");

// Radar chart
lines.push("    const rC = document.getElementById('chart-radar') as HTMLCanvasElement;");
lines.push("    if (rC) {");
lines.push("      const ctx = rC.getContext('2d');");
lines.push("      if (ctx) {");
lines.push("        const dims = ['market','fundamentals','policy','hot_money','social','lockup'];");
lines.push("        const scores = dims.map(d=>extractScore(getFromMsg(messages,d))||5);");
lines.push("        const labels = dims.map(d=>AGENT_LABELS[d]);");
lines.push("        const c = new C(ctx, {");
lines.push("          type: 'radar',");
lines.push("          data: {");
lines.push("            labels,");
lines.push("            datasets: [{");
lines.push("              label: '评分',");
lines.push("              data: scores,");
lines.push("              backgroundColor: 'rgba(0,229,255,0.15)',");
lines.push("              borderColor: '#00E5FF',");
lines.push("              borderWidth: 2,");
lines.push("              pointBackgroundColor: '#00E5FF',");
lines.push("              pointBorderColor: '#fff',");
lines.push("              pointRadius: 4,");
lines.push("            }],");
lines.push("          },");
lines.push("          options: {");
lines.push("            responsive: true, maintainAspectRatio: false,");
lines.push("            plugins: { legend: { display: false } },");
lines.push("            scales: {");
lines.push("              r: {");
lines.push("                beginAtZero: true, max: 10,");
lines.push("                grid: { color: 'rgba(255,255,255,0.08)' },");
lines.push("                ticks: { display: false },");
lines.push("                pointLabels: { color: '#888', font: { size: 10 } },");
lines.push("              },");
lines.push("            },");
lines.push("          },");
lines.push("        });");
lines.push("        inst.push(c);");
lines.push("      }");
lines.push("    }");

lines.push("    chartInstances.current = inst;");
lines.push("  }, [chartLoaded, messages]);");

// ====== UI EFFECTS ======
lines.push("");
lines.push("  useEffect(() => {");
lines.push("    if (!showHint) return;");
lines.push("    const t = setTimeout(() => setShowHint(false), 4000);");
lines.push("    return () => clearTimeout(t);");
lines.push("  }, [showHint]);");

lines.push("  useEffect(() => {");
lines.push("    const f = () => setFullscreen(!!document.fullscreenElement);");
lines.push("    document.addEventListener('fullscreenchange', f);");
lines.push("    return () => document.removeEventListener('fullscreenchange', f);");
lines.push("  }, []);");

lines.push("  const toggleFS = useCallback(async () => {");
lines.push("    const el = containerRef.current;");
lines.push("    if (!el) return;");
lines.push("    if (!document.fullscreenElement) { await el.requestFullscreen(); }");
lines.push("    else { await document.exitFullscreen(); }");
lines.push("  }, []);");

lines.push("  useEffect(() => {");
lines.push("    const el = containerRef.current;");
lines.push("    if (!el) return;");
lines.push("    const handler = (e: KeyboardEvent) => {");
lines.push("      if (e.key === 'ArrowLeft') { setCurrent(p => Math.max(0, p - 1)); e.preventDefault(); }");
lines.push("      else if (e.key === 'ArrowRight') { setCurrent(p => Math.min(TOTAL_PAGES - 1, p + 1)); e.preventDefault(); }");
lines.push("      else if (e.key === 'f' || e.key === 'F') { toggleFS(); }");
lines.push("    };");
lines.push("    el.addEventListener('keydown', handler);");
lines.push("    return () => el.removeEventListener('keydown', handler);");
lines.push("  }, [toggleFS]);");

lines.push("  const handleTouchStart = (e: React.TouchEvent) => { touchX.current = e.touches[0].clientX; };");
lines.push("  const handleTouchEnd = (e: React.TouchEvent) => {");
lines.push("    const diff = touchX.current - e.changedTouches[0].clientX;");
lines.push("    if (Math.abs(diff) > 50) {");
lines.push("      if (diff > 0) setCurrent(p => Math.min(TOTAL_PAGES - 1, p + 1));");
lines.push("      else setCurrent(p => Math.max(0, p - 1));");
lines.push("    }");
lines.push("  };");

// ====== LOADING ======
lines.push("");
lines.push("  if (!chartLoaded && typeof window !== 'undefined') {");
lines.push("    return (");
lines.push("      <div className=\"rounded-2xl border border-[#2a2a2a] bg-[#0f0f0f] p-12 text-center\">");
lines.push("        <div className=\"inline-flex items-center gap-2 text-sm text-[#555]\">");
lines.push("          <span className=\"w-2 h-2 bg-[#ff5a1f] rounded-full animate-pulse\" />");
lines.push("          加载图表库...");
lines.push("        </div>");
lines.push("      </div>");
lines.push("    );");
lines.push("  }");

// ====== PAGE DEFINITIONS ======
lines.push("");
lines.push("  const pages: React.ReactNode[] = [");
lines.push("    // 1: 封面");
lines.push("    <div key=\"c\" className=\"flex flex-col items-center justify-center h-full p-8 text-center\">");
lines.push("      <div className=\"text-5xl mb-4\">{isBullish ? '📈' : isBearish ? '📉' : '📊'}</div>");
lines.push("      <div className=\"text-3xl font-bold text-white mb-2\">{ticker} {tickerName}</div>");
lines.push("      <div className=\"text-sm text-[#555] mb-6\">{tradeDate}</div>");
lines.push("      <div className=\"inline-block px-6 py-2 rounded-full text-lg font-bold mb-4\" style={{backgroundColor: ratingBg, color: ratingColor}}>{ratingTextCN}</div>");
lines.push("      <div className=\"text-lg text-[#aaa] max-w-lg\">{signal?.text || '综合分析报告'}</div>");
lines.push("    </div>,");

lines.push("    // 2: 仪表盘");
lines.push("    <div key=\"d\" className=\"flex flex-col h-full p-6\">");
lines.push("      <div className=\"text-lg font-bold text-white mb-4\">精决策仪表盘</div>");
lines.push("      <div className=\"grid grid-cols-4 gap-3 mb-6\">");
lines.push("        {kpiItems.map((k,i)=>(");
lines.push("          <div key={i} className=\"bg-[#1a1a1a] rounded-xl p-4 text-center border border-[#2a2a2a]\">");
lines.push("            <div className=\"text-xs text-[#555] mb-1\">{k.label}</div>");
lines.push("            <div className=\"text-xl font-bold\" style={{color: k.color || '#fff'}}>{k.value}</div>");
lines.push("          </div>");
lines.push("        ))}");
lines.push("      </div>");
lines.push("      <div className=\"flex-1 flex items-center justify-center\">");
lines.push("        <div className=\"w-full max-w-md\">");
lines.push("          <div className=\"text-sm text-[#555] mb-3 text-center\">多维度评分分布</div>");
lines.push("          <canvas id=\"chart-radar\" height={240} />");
lines.push("        </div>");
lines.push("      </div>");
lines.push("      <div className=\"mt-4\">");
lines.push("        <div className=\"text-xs text-[#555] mb-2\">数据覆盖度</div>");
lines.push("        <div className=\"h-2 bg-[#2a2a2a] rounded-full overflow-hidden\">");
lines.push("          <div className=\"h-full rounded-full transition-all duration-500\" style={{width: coveragePct + '%', background: 'linear-gradient(90deg, #00E5FF, #00E676)'}} />");
lines.push("        </div>");
lines.push("        <div className=\"text-right text-xs text-[#555] mt-1\">{coveragePct}%</div>");
lines.push("      </div>");
lines.push("    </div>,");

lines.push("    // 3: 资金流向");
lines.push("    <div key=\"f\" className=\"flex flex-col h-full p-6\">");
lines.push("      <div className=\"text-lg font-bold text-white mb-4\">资金流向</div>");
lines.push("      <div className=\"flex-1\"><canvas id=\"chart-fund\" height={200} /></div>");
lines.push("      <div className=\"mt-4 p-4 bg-[#1a1a1a] rounded-xl border border-[#2a2a2a]\">");
lines.push("        <div className=\"text-sm text-[#888]\">{extractOneLiner(hotMoneyContent) || '暂无资金数据'}</div>");
lines.push("      </div>");
lines.push("    </div>,");

lines.push("    // 4: 多空对决");
lines.push("    <div key=\"db\" className=\"flex flex-col h-full p-6\">");
lines.push("      <div className=\"text-lg font-bold text-white mb-4\">多空对决</div>");
lines.push("      <div className=\"flex-1\"><canvas id=\"chart-debate\" height={200} /></div>");
lines.push("      <div className=\"mt-4 grid grid-cols-2 gap-3\">");
lines.push("        <div className=\"p-4 bg-[#1a1a1a] rounded-xl border border-[#2a2a2a] text-center\">");
lines.push("          <div className=\"text-xs text-[#555] mb-1\">情绪面</div>");
lines.push("          <div className=\"text-lg font-bold text-[#00E676]\">{extractScore(socialContent) !== null ? extractScore(socialContent) + '/10' : '--'}</div>");
lines.push("        </div>");
lines.push("        <div className=\"p-4 bg-[#1a1a1a] rounded-xl border border-[#2a2a2a] text-center\">");
lines.push("          <div className=\"text-xs text-[#555] mb-1\">资金面</div>");
lines.push("          <div className=\"text-lg font-bold text-[#00E5FF]\">{extractScore(hotMoneyContent) !== null ? extractScore(hotMoneyContent) + '/10' : '--'}</div>");
lines.push("        </div>");
lines.push("      </div>");
lines.push("    </div>,");

lines.push("    // 5: 基本面");
lines.push("    <div key=\"fd\" className=\"flex flex-col h-full p-6\">");
lines.push("      <div className=\"text-lg font-bold text-white mb-4\">基本面分析</div>");
lines.push("      <div className=\"flex-1 overflow-y-auto\">");
lines.push("        <div className=\"p-4 bg-[#1a1a1a] rounded-xl border border-[#2a2a2a]\">");
lines.push("          <div className=\"text-sm text-[#ccc] leading-relaxed whitespace-pre-wrap\">{extractOneLiner(getFromMsg(messages,'fundamentals')) || '基本面数据暂无'}</div>");
lines.push("        </div>");
lines.push("      </div>");
lines.push("    </div>,");

lines.push("    // 6: 政策面");
lines.push("    <div key=\"p\" className=\"flex flex-col h-full p-6\">");
lines.push("      <div className=\"text-lg font-bold text-white mb-4\">政策面分析</div>");
lines.push("      <div className=\"flex-1 overflow-y-auto\">");
lines.push("        <div className=\"p-4 bg-[#1a1a1a] rounded-xl border border-[#2a2a2a]\">");
lines.push("          <div className=\"text-sm text-[#ccc] leading-relaxed whitespace-pre-wrap\">{extractOneLiner(getFromMsg(messages,'policy')) || '政策面数据暂无'}</div>");
lines.push("        </div>");
lines.push("      </div>");
lines.push("    </div>,");

lines.push("    // 7: 情绪面");
lines.push("    <div key=\"s\" className=\"flex flex-col h-full p-6\">");
lines.push("      <div className=\"text-lg font-bold text-white mb-4\">情绪面分析</div>");
lines.push("      <div className=\"grid grid-cols-2 gap-3 mb-4\">");
lines.push("        <div className=\"p-4 bg-[#1a1a1a] rounded-xl border border-[#2a2a2a] text-center\">");
lines.push("          <div className=\"text-xs text-[#555] mb-1\">情绪评分</div>");
lines.push("          <div className=\"text-2xl font-bold text-[#00E5FF]\">{extractScore(socialContent) !== null ? extractScore(socialContent) : '--'}</div>");
lines.push("          <div className=\"text-[10px] text-[#555] mt-1\">/10</div>");
lines.push("        </div>");
lines.push("        <div className=\"p-4 bg-[#1a1a1a] rounded-xl border border-[#2a2a2a] text-center\">");
lines.push("          <div className=\"text-xs text-[#555] mb-1\">市场热度</div>");
lines.push("          <div className=\"text-2xl font-bold text-[#FF6B00]\">{extractScore(marketContent) !== null ? extractScore(marketContent) : '--'}</div>");
lines.push("          <div className=\"text-[10px] text-[#555] mt-1\">/10</div>");
lines.push("        </div>");
lines.push("      </div>");
lines.push("      <div className=\"flex-1 overflow-y-auto\">");
lines.push("        <div className=\"p-4 bg-[#1a1a1a] rounded-xl border border-[#2a2a2a]\">");
lines.push("          <div className=\"text-sm text-[#ccc] leading-relaxed whitespace-pre-wrap\">{extractOneLiner(socialContent) || '情绪数据暂无'}</div>");
lines.push("        </div>");
lines.push("      </div>");
lines.push("    </div>,");

lines.push("    // 8: 技术面");
lines.push("    <div key=\"m\" className=\"flex flex-col h-full p-6\">");
lines.push("      <div className=\"text-lg font-bold text-white mb-4\">市场技术面</div>");
lines.push("      <div className=\"flex-1 overflow-y-auto\">");
lines.push("        <div className=\"p-4 bg-[#1a1a1a] rounded-xl border border-[#2a2a2a] mb-3\">");
lines.push("          <div className=\"text-xs text-[#555] mb-2\">技术指标总结</div>");
lines.push("          <div className=\"text-sm text-[#ccc] leading-relaxed whitespace-pre-wrap\">{extractOneLiner(marketContent) || '市场技术数据暂无'}</div>");
lines.push("        </div>");
lines.push("      </div>");
lines.push("    </div>,");

lines.push("    // 9: 行动指南");
lines.push("    <div key=\"a\" className=\"flex flex-col h-full p-6\">");
lines.push("      <div className=\"text-lg font-bold text-white mb-4\">行动指南</div>");
lines.push("      <div className=\"flex-1 space-y-3\">");
lines.push("        {actionItems.map((item,i)=>(");
lines.push("          <div key={i} className=\"p-4 rounded-xl border\" style={{backgroundColor: item.color + '12', borderColor: item.color + '40'}}>");
lines.push("            <div className=\"flex items-center gap-2 mb-1\">");
lines.push("              <span className=\"text-lg\">{item.emoji}</span>");
lines.push("              <span className=\"font-bold text-sm\" style={{color: item.color}}>{item.role}</span>");
lines.push("            </div>");
lines.push("            <div className=\"text-sm text-[#ccc] ml-7\">{item.action}</div>");
lines.push("          </div>");
lines.push("        ))}");
lines.push("      </div>");
lines.push("    </div>,");

lines.push("    // 10: 总结");
lines.push("    <div key=\"su\" className=\"flex flex-col items-center justify-center h-full p-8 text-center\">");
lines.push("      <div className=\"text-4xl mb-3\">{isBullish ? '🟢' : isBearish ? '🔴' : '🟡'}</div>");
lines.push("      <div className=\"text-xl font-bold text-white mb-4\">总结</div>");
lines.push("      <div className=\"inline-block px-6 py-2 rounded-full text-lg font-bold mb-4\" style={{backgroundColor: ratingBg, color: ratingColor}}>{ratingTextCN}</div>");
lines.push("      <div className=\"text-sm text-[#aaa] max-w-md mb-6\">{ticker} ({tickerName}) 综合评级</div>");
lines.push("      <div className=\"text-xs text-[#555]\">数据来源: A股多代理分析 | {tradeDate}</div>");
lines.push("    </div>,");
lines.push("  ];");

// ====== MAIN RETURN ======
lines.push("");
lines.push("  return (");
lines.push("    <div");
lines.push("      ref={containerRef}");
lines.push("      className=\"relative rounded-2xl border border-[#2a2a2a] bg-[#0f0f0f] overflow-hidden select-none focus:outline-none\"");
lines.push("      style={{ minHeight: '500px' }}");
lines.push("      tabIndex={0}");
lines.push("      onTouchStart={handleTouchStart}");
lines.push("      onTouchEnd={handleTouchEnd}>");
lines.push("      {/* 顶部栏 */}");
lines.push("      <div className=\"absolute top-0 left-0 right-0 z-20 flex items-center justify-between px-4 py-2 bg-gradient-to-b from-[#0f0f0f] to-transparent\">");
lines.push("        <div className=\"text-xs text-[#555]\">{current + 1} / {TOTAL_PAGES}</div>");
lines.push("        <button onClick={toggleFS} className=\"text-xs text-[#555] hover:text-white transition-colors px-2 py-1 rounded hover:bg-[#2a2a2a]\">");
lines.push("          {fullscreen ? '退出全屏' : '□ 全屏'}");
lines.push("        </button>");
lines.push("      </div>");
lines.push("      {/* 幻灯片内容 */}");
lines.push("      <div className=\"w-full\" style={{ height: '500px' }}>");
lines.push("        <div className=\"w-full h-full transition-all duration-300\">{pages[current]}</div>");
lines.push("      </div>");
lines.push("      {/* 底部导航点 */}");
lines.push("      <div className=\"absolute bottom-3 left-0 right-0 z-20 flex justify-center gap-1.5\">");
lines.push("        {pages.map((_,i)=>(");
lines.push("          <button key={i} onClick={()=>setCurrent(i)}");
lines.push("            className=\"w-1.5 h-1.5 rounded-full transition-all\"");
lines.push("            style={{backgroundColor: i === current ? ratingColor : '#333'}} />");
lines.push("        ))}");
lines.push("      </div>");
lines.push("      {/* 翻页提示 */}");
lines.push("      {showHint && (");
lines.push("        <div className=\"absolute bottom-8 left-0 right-0 z-30 flex justify-center animate-fade-out\">");
lines.push("          <div className=\"px-4 py-2 rounded-full bg-[#1a1a1a] text-[10px] text-[#555] border border-[#2a2a2a]\">");
lines.push("            ← → 翻页 | F 全屏");
lines.push("          </div>");
lines.push("        </div>");
lines.push("      )}");
lines.push("    </div>");
lines.push("  );");
lines.push("}");

// ====== WRITE ======
fs.writeFileSync(outPath, lines.join("\n"), "utf-8");
console.log("Written " + lines.length + " lines to " + outPath);
